config/routes.rb
Rails.application.routes.draw do
  
  root 'profiledetails#index'
  devise_for :users

  resources :profiledetails # profile_details
  resources :books
  
  get 'welcome/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
	has_one :author

	accepts_nested_attributes_for :author

	def self.search(search)
  		if search
  			where(["name LIKE ?","%#{search}%"]) 
    	else
    		all
  		end
	end
end

app/models/profiledetail.rb
class Profiledetail < ApplicationRecord
	belongs_to :user

	mount_uploader :resume, ResumeUploader
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profiledetail

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.search(params[:search])
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.build_author
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :price, :availability, :search, author_attributes: [:author_name])
    end
end

app/controllers/profiledetails_controller.rb
class ProfiledetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profiledetail, only: %i[ show edit update destroy ]

  # GET /profiledetails or /profiledetails.json Profile_Details
  def index
    @profiledetails = Profiledetail.all
  end

  # GET /profiledetails/1 or /profiledetails/1.json
  def show
  end

  # GET /profiledetails/new
  def new
    user = current_user
    @profiledetail = user.profiledetail || Profiledetail.new
   end

  # GET /profiledetails/1/edit
  def edit
  end

  # POST /profiledetails or /profiledetails.json
  def create
    @profiledetail = Profiledetail.new(profiledetail_params)

    respond_to do |format|
      if @profiledetail.save
        format.html { redirect_to @profiledetail, notice: "Profiledetail was successfully created." }
        format.json { render :show, status: :created, location: @profiledetail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profiledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiledetails/1 or /profiledetails/1.json
  def update
    respond_to do |format|
      if @profiledetail.update(profiledetail_params)
        format.html { redirect_to @profiledetail, notice: "Profiledetail was successfully updated." }
        format.json { render :show, status: :ok, location: @profiledetail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profiledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiledetails/1 or /profiledetails/1.json
  def destroy
    @profiledetail.destroy
    respond_to do |format|
      format.html { redirect_to profiledetails_url, notice: "Profiledetail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profiledetail
      @profiledetail = current_user.profiledetail
    end

    # Only allow a list of trusted parameters through.
    def profiledetail_params
      params.require(:profiledetail).permit(:first_name, :last_name, :education, :experience, :resume, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiledetails_helper.rb
module ProfiledetailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <%= form_with(model: book, local: true) do |f| %>
      <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
          <ul>
            <% book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <%= f.fields_for :author, @book.author do |p| %>
        <div class="field">
          <%= p.label :author %>
          <%= p.text_field :author_name %>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :price %>
        <%= f.number_field :price %>
      </div>

       

      <div class="field">
        <%= f.label :availability %>
        <%= f.check_box :availability %>
      </div>

      <br/>
     
      <div class="actions">
        <%= f.submit %>
      </div>

    <% end %>    
  </div>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Books</h2>

<%= form_tag books_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
<% end %>

<br/>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Availability</th>
      <th> Author </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.price %></td>
        <td><%= book.availability %></td>
        <td><%= book.author.author_name %></td>
       <!--  <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
       <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @book.availability %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
   
  </head>

  <body>

    <%= render 'welcome/header'%>
    <div class="container-fluid">

    <% if notice || alert %>
      <%= render 'layouts/alerts'%>
    <% end %>
    
    

      <br/>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/profiledetails/_form.html.erb
<%= form_with(model: profiledetail, local: true) do |form| %>
  <% if profiledetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profiledetail.errors.count, "error") %> prohibited this profiledetail from being saved:</h2>

      <ul>
        <% profiledetail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :education %>
    <%= form.text_field :education %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.text_field :experience %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :profiledetail_user_id, class: "form-control", value: current_user.id, type: :hidden  %>
  </div>
  
  <div class="field">
    <%= form.label :resume %>
    <%= form.file_field :resume, accept: 'image/png, image/jpg' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiledetails/edit.html.erb
<h1>Editing Profiledetail</h1>

<%= render 'form', profiledetail: @profiledetail %>

<%= link_to 'Show', @profiledetail %> |
<%= link_to 'Back', profiledetails_path %>

app/views/profiledetails/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Profile</h2>

<table class="table">
  <thead class = "table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Education</th>
      <th>Experience</th>
      <th>Resume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiledetails.each do |profiledetail| %>
      <tr>
        <td><%= profiledetail.first_name %></td>
        <td><%= profiledetail.last_name %></td>
        <td><%= profiledetail.education %></td>
        <td><%= profiledetail.experience %></td>
        <td><%= profiledetail.resume %></td>
 <!--       <td><%= link_to 'Show', profiledetail %></td> -->
        <td><%= link_to 'Edit', edit_profiledetail_path(profiledetail) %></td>
        <td><%= link_to 'Destroy', profiledetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profiledetail', new_profiledetail_path %>

app/views/profiledetails/new.html.erb
<div class="card text-center">
  <div class="card-header">
    Register Your Profile
  </div>
  <div class="card-body">
   <%= render 'form', profiledetail: @profiledetail %>
  </div>
</div>

<%= link_to 'Back', profiledetails_path %>

app/views/profiledetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profiledetail.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profiledetail.last_name %>
</p>

<p>
  <strong>Education:</strong>
  <%= @profiledetail.education %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @profiledetail.experience %>
</p>

<p>
  <strong>Resume:</strong>
  <%= image_tag @profiledetail.resume.url %>
</p>

<%= link_to 'Edit', edit_profiledetail_path(@profiledetail) %> |
<%= link_to 'Back', profiledetails_path %>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Profile Website', root_path, class:"navbar-brand"%>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>  
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit User", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class ="nav-item">
            <%= link_to "Books", books_path ,class: "nav-link" %>
          </li>        
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        
      </ul>
     
    </div>
  </div>
</nav>

app/views/welcome/about.html.erb
<h1>About US</h1>

app/views/welcome/home.html.erb
<h1>Profile Registration</h1>
FirstName
LastName
Education
Experience
CV Attachment



rails g scaffold profile first_name:string last_name:string education:string experience:string resume:binary